In [1]:
import numpy as np

In [2]:
X = np.array([[1,1,1],[1,1,0], [1,1,1],[0,1,1], [1,0,1] , [0,1,1], [1,0,0]])

Y = np.array([[7.52],[14.83],[12.91] ])

In [3]:
np.dot(X,Y) 

array([[35.26],
       [22.35],
       [35.26],
       [27.74],
       [20.43],
       [27.74],
       [ 7.52]])

In [8]:
Y = np.array([[7.52],[14.83],[12.91] ])
Z = np.array([[1,0,0],[0,1,0], [0,0,.8]])

In [11]:
Z

array([[1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 0.8]])

In [13]:
np.dot(Z,Y)

array([[ 7.52 ],
       [14.83 ],
       [10.328]])

In [14]:
new_Y = np.dot(Z,Y)

In [15]:
new_Y

array([[ 7.52 ],
       [14.83 ],
       [10.328]])

In [16]:
np.dot(X,new_Y)

array([[32.678],
       [22.35 ],
       [32.678],
       [25.158],
       [17.848],
       [25.158],
       [ 7.52 ]])

In [17]:
np.dot(X,Y) - np.dot(X,new_Y)

array([[2.582],
       [0.   ],
       [2.582],
       [2.582],
       [2.582],
       [2.582],
       [0.   ]])

In [5]:
A = np.array([[5,21,6],[11,8,62]])

B = np.array([[1,2],[4,5],[1,1],[2,2] ])

In [6]:
X + Y
 

ValueError: operands could not be broadcast together with shapes (4,3) (4,2) 

In [16]:
a = np.array([[2,3]])
b = np.array([[-2,-3]])

In [17]:
a.shape

(1, 2)

In [14]:
a_reshaped = a.reshape(2,1)

In [18]:
np.dot(a,b)

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [4]:
s = np.array([[[1,2],[3,4]],[[5,6],[7,8]], [[9,10],[11,12]]  ])
m = np.array([[[-2,-2],[3,14]],[[15,-2],[7,8]], [[29,10],[21,32]]  ])


In [5]:
s[0]  + m[1]

array([[16,  0],
       [10, 12]])

In [8]:
print(s[0]) 

[[1 2]
 [3 4]]


In [9]:
print(m[1]) 

[[15 -2]
 [ 7  8]]


In [11]:
m = np.array([[1,1,4],[1,0,2],[4,2,5]])

In [12]:
print(m)

[[1 1 4]
 [1 0 2]
 [4 2 5]]


In [13]:
print(m*m.T)

[[ 1  1 16]
 [ 1  0  4]
 [16  4 25]]


In [15]:
M_T = m.T

In [21]:
M_T

array([[1, 1, 4],
       [1, 0, 2],
       [4, 2, 5]])

In [20]:
np.dot(m,(m.T))

array([[18,  9, 26],
       [ 9,  5, 14],
       [26, 14, 45]])

In [36]:
S = np.array([[1,2,2],[3,5,12],[10,9,8]])

In [37]:
S = np.array([[3,2,2],[3,5,12],[10,9,8]])

In [2]:
A = np.array([[5,21,6],[11,8,62]])
B = np.array([[4,3],[6,7],[10,3 ] ])


np.dot(A,B)


array([[206, 180],
       [712, 275]])

In [3]:
print(A)

[[ 5 21  6]
 [11  8 62]]
