In [2]:
import numpy as np

Scalars

In [3]:
s = 5

In [4]:
s

5

Vector

In [5]:
v = np.array([5,-2,4])

In [6]:
v

array([ 5, -2,  4])

Matrices

In [7]:
m = np.array([[5,12,6],[-2,0,14]])

In [8]:
m

array([[ 5, 12,  6],
       [-2,  0, 14]])

In [9]:
print(m)

[[ 5 12  6]
 [-2  0 14]]


Data Types

In [12]:
type(s)


int

In [14]:
type(v) #N dimesional array

numpy.ndarray

In [13]:
type(m)

numpy.ndarray

Data Shapes

In [36]:
m.shape #2 * 3 matrix

(2, 3)

In [37]:
v.shape  #have 3 elements

(3,)

Creating column vector

In [42]:
v.reshape(1,3) #row vector

array([[ 5, -2,  4]])

In [43]:
v.reshape(3,1) #column vector

array([[ 5],
       [-2],
       [ 4]])

In [44]:
print(m)

[[ 5 12  6]
 [-2  0 14]]


In [41]:
print(m.reshape(3,2))

[[ 5 12]
 [ 6 -2]
 [ 0 14]]
